[package]
build = "build.rs"
name = "utpm"
version = "3.0.0"
edition = "2021"
links = "git2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.0"
toml = { version = "^0.8.14", features = ["display"] }
inquire = "0.6.2"
semver = { version = "1.0.18", features = ["serde"] }
spdx = { version = "0.10.2", features = ["text"] }
clap = { version = "4.4.2", features = ["derive"] }
git2 = "0.18.0"
owo-colors = "3.5.0"
strum = { version = "0.26.2", features = ["derive"] }
typst-project = { git = "https://github.com/tingerrr/typst-project", rev = "8462942ef0c783acf339e715b5e24b2dba423de1" }
openssl = { version = "0.10", features = ["vendored"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = "0.3.18"
clap_complete = "4.5.12"
shadow-rs = "0.31.1"

[[bin]]
name = "utpm"
path = "src/main.rs"

[[bin]]
name = "utpm-ci"
path = "src/ci.rs"

[features]
ci = []

# For future dependencies check and other things, it will be usefull
# Reduce size
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
